import React from "react";
import OxhainBanner from "../../Components/Banner/Banner04";

const Terms = () => {
    return (
        <div className="flex flex-col items-start justify-start w-full terms-control-section font-prompt my-20">
            <OxhainBanner  
                className="xsm:mb-5 lg:mb-8 xl:mb-8 2xl:mb-12"
                titleclassname="mt-5"
                breadcrumblink01="/terms"
                breadcrumb01="Legal"
                breadcrumblink02="/terms"
                breadcrumb02="Terms of Use"
                title="Oxhain Terms of Use"
                content="Last revised: 12 July 2022"
            />
            <div className="flex flex-col container mx-auto xsm:px-5 lg:px-2 xl:px-2 2xl:px-2 xsm:mb-5 lg:mb-5 xl:mb-5 2xl:mb-8 text-left">
                <p className="font-normal xsm:text-sm lg:text-sm xl:text-base 2xl:text-lg text4">These Oxhain Terms of Use is entered into between you (hereinafter referred to as “you” or “your”) and Oxhain operators (as defined below). By accessing, downloading, using or clicking on “I agree” to accept any Oxhain Services (as defined below) provided by Oxhain (as defined below), you agree that you have read, understood and accepted all of the terms and conditions stipulated in these Terms of Use (hereinafter referred to as “these Terms”) as well as our Privacy Policy at www.oxhain.com/en/privacy. In addition, when using some features of the Services, you may be subject to specific additional terms and conditions applicable to those features.</p>
                <p className="font-normal xsm:text-sm lg:text-sm xl:text-base 2xl:text-lg text4">Please read the terms carefully as they govern your use of Oxhain Services.THESE TERMS CONTAIN IMPORTANT PROVISIONS INCLUDING AN ARBITRATION PROVISION THAT REQUIRES ALL CLAIMS TO BE RESOLVED BY WAY OF LEGALLY BINDING ARBITRATION. The terms of the arbitration provision are set forth in Article</p>
                <p className="font-normal xsm:text-sm lg:text-sm xl:text-base 2xl:text-lg text4">10, “Resolving Disputes: Forum, Arbitration, Class Action Waiver”, hereunder. As with any asset, the values of Digital Currencies (as defined below) may fluctuate significantly and there is a substantial risk of economic losses when purchasing, selling, holding or investing in Digital Currencies and their derivatives.</p>
                <p className="font-normal xsm:text-sm lg:text-sm xl:text-base 2xl:text-lg text4">BY MAKING USE OF BINANCE SERVICES, YOU ACKNOWLEDGE AND AGREE THAT: (1) YOU ARE AWARE OF THE RISKS ASSOCIATED WITH TRANSACTIONS OF DIGITAL CURRENCIES AND THEIR DERIVATIVES; (2) YOU SHALL ASSUME ALL RISKS RELATED TO THE USE OF BINANCE SERVICES AND TRANSACTIONS OF DIGITAL CURRENCIES AND THEIR DERIVATIVES; AND (3) BINANCE SHALL NOT BE LIABLE FOR ANY SUCH RISKS OR ADVERSE OUTCOMES.</p>
                <p className="font-normal xsm:text-sm lg:text-sm xl:text-base 2xl:text-lg text4">By accessing, using or attempting to use Oxhain Services in any capacity, you acknowledge that you accept and agree to be bound by these Terms. If you do not agree, do not access Oxhain or utilize Oxhain services.</p>
                <p className="font-normal xsm:text-sm lg:text-sm xl:text-base 2xl:text-lg text4">If you would like to know more about the risks associated with investing in or trading Digital Assets, you can access our General Risk Warning at www.oxhain.com/en/risk-warning.</p>
            </div>
            <div className="flex flex-col container mx-auto xsm:px-5 lg:px-2 xl:px-2 2xl:px-2 xsm:mb-5 lg:mb-8 xl:mb-11 2xl:mb-11 text-left">
                <h4 className="text5 xsm:text-base lg:text-base xl:text-lg 2xl:text-lg font-medium mb-5">I. Definitions</h4>
                <ol>
                    <li className="font-normal xsm:text-sm lg:text-sm xl:text-base 2xl:text-lg text4 xsm:mb-3 lg:mb-3 xl:mb-5 2xl:mb-8"><strong className="text5 font-normal mr-3">1. Oxhain refers</strong>to an ecosystem comprising Oxhain websites (whose domain names include but are not limited to https://www.oxhain.com/en), mobile applications, clients, applets and other applications that are developed to offer Oxhain Services, and includes independently-operated platforms, websites and clients within the ecosystem (e.g. Oxhain’s Open Platform, Oxhain Launchpad, Oxhain Labs, Oxhain Charity, Oxhain DEX, Oxhain X, JEX, Trust Wallet, and fiat gateways). In case of any inconsistency between relevant terms of use of the above platforms and the contents of these Terms, the respective applicable terms of such platforms shall prevail.</li>
                    <li className="font-normal xsm:text-sm lg:text-sm xl:text-base 2xl:text-lg text4 xsm:mb-3 lg:mb-3 xl:mb-5 2xl:mb-8"><strong className="text5 font-normal mr-3">2. Oxhain Operators</strong>refer to all parties that run Oxhain, including but not limited to legal persons (including Oxhain UAB), unincorporated organizations and teams that provide Oxhain Services and are responsible for such services. For convenience, unless otherwise stated, references to “Oxhain” and “we” in these Terms specifically mean Oxhain Operators. UNDER THESE TERMS, BINANCE OPERATORS MAY CHANGE AS BINANCE’S BUSINESS ADJUSTS, IN WHICH CASE, THE CHANGED OPERATORS SHALL PERFORM THEIR OBLIGATIONS UNDER THESE TERMS WITH YOU AND PROVIDE SERVICES TO YOU, AND SUCH CHANGE DOES NOT AFFECT YOUR RIGHTS AND INTERESTS UNDER THESE TERMS. ADDITIONALLY, THE SCOPE OF BINANCE OPERATORS MAY BE EXPANDED DUE TO THE PROVISION OF NEW BINANCE SERVICES, IN WHICH CASE, IF YOU CONTINUE TO USE BINANCE SERVICES, IT IS DEEMED THAT YOU HAVE AGREED TO JOINTLY EXECUTE THESE TERMS WITH THE NEWLY ADDED BINANCE OPERATORS. IN CASE OF A DISPUTE, YOU SHALL DETERMINE THE ENTITIES BY WHICH THESE TERMS ARE PERFORMED WITH YOU AND THE COUNTERPARTIES OF THE DISPUTE, DEPENDING ON THE SPECIFIC SERVICES YOU USE AND THE PARTICULAR ACTIONS THAT AFFECT YOUR RIGHTS OR INTERESTS.</li>
                    <li className="font-normal xsm:text-sm lg:text-sm xl:text-base 2xl:text-lg text4 xsm:mb-3 lg:mb-3 xl:mb-5 2xl:mb-8"><strong className="text5 font-normal mr-3">3. Oxhain Services</strong>refer to various services provided to you by Oxhain that are based on Internet and/or blockchain technologies and offered via Oxhain websites, mobile applications, clients and other forms (including new ones enabled by future technological development). Oxhain Services include but are not limited to such Oxhain ecosystem components as Digital Asset Trading Platforms, the financing sector, Oxhain Labs, Oxhain Academy, Oxhain Charity, Oxhain Info, Oxhain Launchpad, Oxhain Research, Oxhain Chain, Oxhain X, Oxhain Fiat Gateway, existing services offered by Trust Wallet and novel services to be provided by Oxhain.</li>
                    <li className="font-normal xsm:text-sm lg:text-sm xl:text-base 2xl:text-lg text4 xsm:mb-3 lg:mb-3 xl:mb-5 2xl:mb-8"><strong className="text5 font-normal mr-3">4. Oxhain Platform Rules</strong>refer to all rules, interpretations, announcements, statements, letters of consent and other contents that have been and will be subsequently released by Oxhain, as well as all regulations, implementation rules, product process descriptions, and announcements published in the Help Center or within products or service processes.</li>
                    <li className="font-normal xsm:text-sm lg:text-sm xl:text-base 2xl:text-lg text4 xsm:mb-3 lg:mb-3 xl:mb-5 2xl:mb-8"><strong className="text5 font-normal mr-3">5. Users</strong>refer to all individuals, institutions or organizations that access, download or use Oxhain or Oxhain Services and who meet the criteria and conditions stipulated by Oxhain. If there exist other agreements for such entities as developers, distributors, market makers, and Digital Currencies exchanges, such agreements shall be followed.</li>
                    <li className="font-normal xsm:text-sm lg:text-sm xl:text-base 2xl:text-lg text4 xsm:mb-3 lg:mb-3 xl:mb-5 2xl:mb-8"><strong className="text5 font-normal mr-3">6. Digital Currencies</strong>refer to encrypted or digital tokens or cryptocurrencies with a certain value that are based on blockchain and cryptography technologies and are issued and managed in a decentralized form.</li>
                    <li className="font-normal xsm:text-sm lg:text-sm xl:text-base 2xl:text-lg text4 xsm:mb-3 lg:mb-3 xl:mb-5 2xl:mb-8"><strong className="text5 font-normal mr-3">7. Digital Assets</strong>refer to Digital Currencies, their derivatives or other types of digitalized assets with a certain value.</li>
                    <li className="font-normal xsm:text-sm lg:text-sm xl:text-base 2xl:text-lg text4 xsm:mb-3 lg:mb-3 xl:mb-5 2xl:mb-8"><strong className="text5 font-normal mr-3">8. Oxhain Accounts</strong>refer to the foundational virtual accounts, including main accounts and subaccounts, which are opened by Oxhain for Users to record on Oxhain their usage of Oxhain Services, transactions, asset changes and basic information. Oxhain Accounts serve as the basis for Users to enjoy and exercise their rights on Oxhain.</li>
                    <li className="font-normal xsm:text-sm lg:text-sm xl:text-base 2xl:text-lg text4 xsm:mb-3 lg:mb-3 xl:mb-5 2xl:mb-8"><strong className="text5 font-normal mr-3">9. Crypto-to-crypto Trading</strong>refers to spot transactions in which one digital currency is exchanged for another digital currency.</li>
                    <li className="font-normal xsm:text-sm lg:text-sm xl:text-base 2xl:text-lg text4 xsm:mb-3 lg:mb-3 xl:mb-5 2xl:mb-8"><strong className="text5 font-normal mr-3">10. Fiat Trading</strong>refers to spot transactions in which Digital Currencies are exchanged for fiat currencies or vice versa.</li>
                    <li className="font-normal xsm:text-sm lg:text-sm xl:text-base 2xl:text-lg text4 xsm:mb-3 lg:mb-3 xl:mb-5 2xl:mb-8"><strong className="text5 font-normal mr-3">11. Collateral Accounts</strong>refer to special accounts opened by Users on Oxhain to deposit and withdraw collateral (such as margins) in accordance with these Terms (including the Oxhain Contract Services Agreement and Oxhain Platform Rules), as required for contract transactions, leveraged trading and/or currency borrowing services.</li>
                    <li className="font-normal xsm:text-sm lg:text-sm xl:text-base 2xl:text-lg text4 xsm:mb-3 lg:mb-3 xl:mb-5 2xl:mb-8"><strong className="text5 font-normal mr-3">12. Loan/Lending</strong>refers to Oxhain’s lending of Digital Currencies to Users at an interest collected in certain ways (in the form of Digital Currencies), including but not limited to the leveraged trading and currency lending services currently offered, and other forms of loan/lending services to be launched by Oxhain.</li>
                    <li className="font-normal xsm:text-sm lg:text-sm xl:text-base 2xl:text-lg text4"><strong className="text5 font-normal mr-3">13. KYC</strong>refers to the “know-your-customer” process that Oxhain has put in place before entering into a business relationship or conducting transactions with its Users. As part of this process, Oxhain may do anything that it deems necessary in order to identify Users, verify their identity, scrutinize and investigate User transactions, or comply with any applicable law or regulation.</li>
                </ol>
            </div>
            <div className="flex flex-col container mx-auto xsm:px-5 lg:px-2 xl:px-2 2xl:px-2 xsm:mb-3 lg:mb-5 xl:mb-5 2xl:mb-8 text-left">
                <h4 className="text5 xsm:text-base lg:text-base xl:text-lg 2xl:text-lg font-medium xsm:mb-5 lg:mb-5 xl:mb-8 2xl:mb-8">II. General Provisions</h4>
                <h5 className="text5 xsm:text-base lg:text-base xl:text-lg 2xl:text-lg font-normal xsm:mb-3 lg:mb-3 xl:mb-5 2xl:mb-5">1. About These Terms</h5>
                <div className="flex flex-col justify-start items-start xsm:mt-2 lg:mt-4 xl:mt-4 2xl:mt-4 xsm:mb-8 lg:mb-8 xl:mb-12 2xl:mb-16">
                    <p className="font-normal xsm:text-sm lg:text-sm xl:text-base 2xl:text-lg text4 xsm:mb-3 lg:mb-3 xl:mb-5 2xl:mb-5"><strong className="text5 font-normal mr-3 w-full block">a. Contractual Relationship</strong>These Terms constitute a legal agreement and create a binding contract between you and Oxhain Operators.</p>
                    <p className="font-normal xsm:text-sm lg:text-sm xl:text-base 2xl:text-lg text4 xsm:mb-3 lg:mb-3 xl:mb-5 2xl:mb-5"><strong className="text5 font-normal mr-3 w-full block">b. Supplementary Terms</strong>Due to the rapid development of Digital Currencies and Oxhain, these Terms between you and Oxhain Operators do not enumerate or cover all rights and obligations of each party, and do not guarantee full alignment with needs arising from future development. Therefore,THE PRIVACY POLICY (（）), BINANCE PLATFORM RULES, AND ALL OTHER AGREEMENTS ENTERED INTO SEPARATELY BETWEEN YOU AND BINANCE ARE DEEMED SUPPLEMENTARY TERMS THAT ARE AN INTEGRAL PART OF THESE TERMS AND SHALL HAVE THE SAME LEGAL EFFECT. YOUR USE OF BINANCE SERVICES IS DEEMED YOUR ACCEPTANCE OF THE ABOVE SUPPLEMENTARY TERMS.</p>
                    <p className="font-normal xsm:text-sm lg:text-sm xl:text-base 2xl:text-lg text4 xsm:mb-3 lg:mb-3 xl:mb-5 2xl:mb-5"><strong className="text5 font-normal mr-3 w-full block">c. Changes to These Terms</strong>Oxhain reserves the right to change or modify these Terms in its discretion at any time. Oxhain will notify such changes by updating the terms on its website () and modifying the [Last revised] date displayed on this page.。ANY AND ALL MODIFICATIONS OR CHANGES TO THESE TERMS WILL BECOME EFFECTIVE UPON PUBLICATION ON THE WEBSITE OR RELEASE TO USERS. THEREFORE, YOUR CONTINUED USE OF BINANCE SERVICES IS DEEMED YOUR ACCEPTANCE OF THE MODIFIED AGREEMENT AND RULES. IF YOU DO NOT AGREE TO ANY CHANGES TO THESE TERMS, YOU MUST STOP USING BINANCE SERVICES IMMEDIATELY. YOU ARE RECOMMENDED TO FREQUENTLY REVIEW THESE TERMS TO ENSURE YOUR UNDERSTANDING OF THE TERMS AND CONDITIONS THAT APPLY TO YOUR ACCESS TO AND USE OF BINANCE SERVICES.</p>
                    <p className="font-normal xsm:text-sm lg:text-sm xl:text-base 2xl:text-lg text4"><strong className="text5 font-normal mr-3 w-full block">d. Prohibition of Use</strong>BY ACCESSING AND USING BINANCE SERVICES, YOU REPRESENT AND WARRANT THAT YOU HAVE NOT BEEN INCLUDED IN ANY TRADE EMBARGOES OR ECONOMIC SANCTIONS LIST (SUCH AS THE UNITED NATIONS SECURITY COUNCIL SANCTIONS LIST), THE LIST OF SPECIALLY DESIGNATED NATIONALS MAINTAINED BY OFAC (THE OFFICE OF FOREIGN ASSETS CONTROL OF THE U.S. DEPARTMENT OF THE TREASURY), OR THE DENIED PERSONS OR ENTITY LIST OF THE U.S. DEPARTMENT OF COMMERCE. BINANCE RESERVES THE RIGHT TO CHOOSE MARKETS AND JURISDICTIONS TO CONDUCT BUSINESS, AND MAY RESTRICT OR REFUSE, IN ITS DISCRETION, THE PROVISION OF BINANCE SERVICES IN CERTAIN COUNTRIES OR REGIONS.</p>
                </div>
                <h5 className="text5 xsm:text-base lg:text-base xl:text-lg 2xl:text-lg font-normal xsm:mb-3 lg:mb-3 xl:mb-5 2xl:mb-5">2. About Oxhain</h5>
                <div className="flex flex-col justify-start items-start xsm:mt-2 lg:mt-4 xl:mt-4 2xl:mt-4 xsm:mb-5 lg:mb-5 xl:mb-8 2xl:mb-8">
                    <p className="font-normal xsm:text-sm lg:text-sm xl:text-base 2xl:text-lg text4">As an important part of the Oxhain Ecosystem, Oxhain mainly serves as a global online platform for Digital Assets trading, and provides Users with a trading platform, financing services, technical services and other Digital Assets-related services. As further detailed in Article 3 below, Users must register and open an account with Oxhain, and deposit Digital Assets into their account prior to trading. Users may, subject to the restrictions set forth in these Terms, apply for the withdrawal of Digital Assets.</p>
                    <p className="font-normal xsm:text-sm lg:text-sm xl:text-base 2xl:text-lg text4">Although Oxhain has been committed to maintaining the accuracy of the information provided through Oxhain Services, Oxhain cannot and does not guarantee its accuracy, applicability, reliability, integrity, performance or appropriateness, nor shall Oxhain be liable for any loss or damage that may be caused directly or indirectly by your use of these contents. The information about Oxhain Services may change without notice, and the main purpose of providing such information is to help Users make independent decisions. Oxhain does not provide investment or consulting advice of any kind, and is not responsible for the use or interpretation of information on Oxhain or any other communication medium. All Users of Oxhain Services must understand the risks involved in Digital Assets trading, and are recommended to exercise prudence and trade responsibly within their own capabilities.</p>
                </div>
                <h5 className="text5 xsm:text-base lg:text-base xl:text-lg 2xl:text-lg font-normal xsm:mb-3 lg:mb-3 xl:mb-5 2xl:mb-5">3. Oxhain Account Registration and Requirements</h5>
                <div className="flex flex-col justify-start items-start xsm:mt-2 lg:mt-4 xl:mt-4 2xl:mt-4">
                    <p className="font-normal xsm:text-sm lg:text-sm xl:text-base 2xl:text-lg text4"><strong className="text5 font-normal mr-3 block w-full xsm:mb-5 lg:mb-5 xl:mb-8 2xl:mb-8">a. Registration</strong>All Users must apply for a Oxhain Account at (https://accounts.oxhain.com/en/register) before using Oxhain Services. When you register a Oxhain Account, you must provide the information identified in this paragraph 3 or otherwise as requested by Oxhain, and accept these Terms, the Privacy Policy, and other Oxhain Platform Rules. Oxhain may refuse, in its discretion, to open a Oxhain Account for you. You agree to provide complete and accurate information when opening a Oxhain Account, and agree to timely update any information you provide to Oxhain to maintain the integrity and accuracy of the information. Each User (including natural person, business or legal entity) may maintain only one main account at any given time. However, Users can open one or more subaccounts under the main account with the consent of Oxhain. For certain Oxhain Services, you may be required to set up a specific account independent from your Oxhain Account, based on the provisions of these Terms or the Supplementary Terms. The registration, use, protection and management of such trading accounts are equally governed by the provisions of this Section and Section VI, unless otherwise stated in these Terms or the Supplementary Terms.</p>
                </div>
            </div>
        </div>
    );
};

export default Terms;